// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsBIOWc--SyRc8mqLUQm59lVc9Aeu--hE',
    appId: '1:446716266560:web:8d633163215aca469bb7a5',
    messagingSenderId: '446716266560',
    projectId: 'nhaidaar-maos',
    authDomain: 'nhaidaar-maos.firebaseapp.com',
    storageBucket: 'nhaidaar-maos.appspot.com',
    measurementId: 'G-K8T2QJF7Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC66w2SbT9P7ppadKkaB6oGb6_CbrBd20',
    appId: '1:446716266560:android:1a40091365e1fff89bb7a5',
    messagingSenderId: '446716266560',
    projectId: 'nhaidaar-maos',
    storageBucket: 'nhaidaar-maos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAttW9Ed7w_KQ3Kn0_roOTEUeRuNwAqY8I',
    appId: '1:446716266560:ios:05942e43a70826f79bb7a5',
    messagingSenderId: '446716266560',
    projectId: 'nhaidaar-maos',
    storageBucket: 'nhaidaar-maos.appspot.com',
    androidClientId: '446716266560-q1mg8eiulcdvpl9990q2e5uac15jcgq1.apps.googleusercontent.com',
    iosClientId: '446716266560-jr186u19aq4kpqiharblph66acrkurns.apps.googleusercontent.com',
    iosBundleId: 'com.example.maos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAttW9Ed7w_KQ3Kn0_roOTEUeRuNwAqY8I',
    appId: '1:446716266560:ios:7aac335d287014af9bb7a5',
    messagingSenderId: '446716266560',
    projectId: 'nhaidaar-maos',
    storageBucket: 'nhaidaar-maos.appspot.com',
    androidClientId: '446716266560-q1mg8eiulcdvpl9990q2e5uac15jcgq1.apps.googleusercontent.com',
    iosClientId: '446716266560-riu2rvh2btuo6mt0sk2amf5qrq2ioclg.apps.googleusercontent.com',
    iosBundleId: 'com.example.maos.RunnerTests',
  );
}
